In [1377]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import datetime

In [1378]:
CreditRisk_df = pd.read_csv("CreditRisk.csv", parse_dates=['Date Funded',"Date_Started"])
CreditRisk_df

,Funded Days,Avg Bank Balance,Avg Bank Negative Days,Max Sell Rate,Max Offer Amount,Date Funded,Sum_Balance Per GL,NAICS Code,Average Net Deposits,Funded Units,...,Risk Tier,ISO Group,Lag Days,App Type,FP Original Term (Months),Paid %,FP Contract Number,Account Status,Baseline Pace %,Original Advance Amount
0,1390.0,8453.56,0.17,1.370,21500.0,2017-10-05,NaN,484110.0,88760.00,1,...,NaN,WHO,0.0,NEW,10.0,1.00,MC171004025,WROFF,34.29,46000.0
1,1252.0,4682.50,0.00,1.524,8000.0,2018-02-20,NaN,423610.0,9879.19,1,...,NaN,WHO,0.0,NEW,8.0,1.00,MC180216046,WROFF,25.11,3000.0
2,1648.0,7106.21,0.75,1.390,22000.0,2017-01-20,NaN,238990.0,42456.00,1,...,NaN,WHO,0.0,NEW,7.0,1.00,MC170118065,WROFF,43.92,65000.0
3,1449.0,2067.44,0.00,1.440,11000.0,2017-08-07,NaN,238320.0,15344.20,1,...,NaN,WHO,0.0,NEW,9.0,1.00,MC170727096,WROFF,86.01,15495.0
4,1449.0,9548.01,0.88,1.500,53000.0,2017-08-07,NaN,238110.0,71789.20,1,...,NaN,WHO,0.0,NEW,10.0,1.00,MC170802165,WROFF,34.52,55000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24204,1008.0,8700.12,2.00,1.479,71000.0,2018-10-22,NaN,621610.0,68449.60,1,...,Ultra-Low Risk,DIR,918.0,NEW,9.0,0.31,MC181005127,WROFF,43.56,NaN
24205,1088.0,1996.29,0.83,1.399,15395.0,2018-08-03,NaN,446191.0,14947.00,1,...,Ultra-Low Risk,DIR,9.0,NEW,9.0,0.16,MC180731041,WROFF,52.50,NaN
24206,962.0,11387.10,0.86,1.489,15000.0,2018-12-07,NaN,453991.0,13685.10,1,...,Ultra-Low Risk,DIR,763.0,NEW,12.0,0.54,MC181205127,WROFF,65.43,NaN
24207,1032.0,4666.67,0.00,1.479,48000.0,2018-09-28,NaN,448140.0,52577.40,1,...,Ultra-Low Risk,DIR,987.0,NEW,8.0,0.13,MC180925221,WROFF,21.90,NaN
24208,1041.0,8514.15,0.83,1.479,101000.0,2018-09-19,NaN,238220.0,111379.00,1,...,Ultra-Low Risk,DIR,116.0,NEW,9.0,0.47,MC180914153,WROFF,82.14,NaN

In [1379]:
CreditRisk_df.shape

(24209, 29)

In [1380]:
CreditRisk_df.isnull().sum()

Funded Days                      3
Avg Bank Balance                39
Avg Bank Negative Days          39
Max Sell Rate                    0
Max Offer Amount                 1
Date Funded                      0
Sum_Balance Per GL           21955
NAICS Code                       1
Average Net Deposits          1570
Funded Units                     0
Gross Annual Sales               0
Portfolio Grade                  3
Avg Number of Deposits          38
Date_Started                     0
Contract Number                  5
R360 Reliant Score           22690
Primary Owner FICO Score       126
Corp Zip                         0
Submissions                      0
Risk Tier                      817
ISO Group                        0
Lag Days                         3
App Type                         0
FP Original Term (Months)        3
Paid %                           3
FP Contract Number               1
Account Status                   3
Baseline Pace %                  3
Original Advance Amount      12026
dtype: int64

In [1381]:
CreditRisk_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24209 entries, 0 to 24208
Data columns (total 29 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Funded Days                24206 non-null  float64
 1   Avg Bank Balance           24170 non-null  float64
 2   Avg Bank Negative Days     24170 non-null  float64
 3   Max Sell Rate              24209 non-null  float64
 4   Max Offer Amount           24208 non-null  float64
 5   Date Funded                24209 non-null  datetime64[ns]
 6   Sum_Balance Per GL         2254 non-null   float64
 7   NAICS Code                 24208 non-null  float64
 8   Average Net Deposits       22639 non-null  float64
 9   Funded Units               24209 non-null  int64
 10  Gross Annual Sales         24209 non-null  float64
 11  Portfolio Grade            24206 non-null  float64
 12  Avg Number of Deposits     24171 non-null  float64
 13  Date_Started               24209 non-null  datetime64[ns]
 14  Contract Number            24204 non-null  object
 15  R360 Reliant Score         1519 non-null   float64
 16  Primary Owner FICO Score   24083 non-null  float64
 17  Corp Zip                   24209 non-null  object
 18  Submissions                24209 non-null  int64
 19  Risk Tier                  23392 non-null  object
 20  ISO Group                  24209 non-null  object
 21  Lag Days                   24206 non-null  float64
 22  App Type                   24209 non-null  object
 23  FP Original Term (Months)  24206 non-null  float64
 24  Paid %                     24206 non-null  float64
 25  FP Contract Number         24208 non-null  object
 26  Account Status             24206 non-null  object
 27  Baseline Pace %            24206 non-null  float64
 28  Original Advance Amount    12183 non-null  float64
dtypes: datetime64[ns](2), float64(18), int64(2), object(7)
memory usage: 5.4+ MB

In [1383]:
CreditRisk_df.columns

Index(['Funded Days', 'Avg Bank Balance', 'Avg Bank Negative Days',
       'Max Sell Rate', 'Max Offer Amount', 'Date Funded',
       'Sum_Balance Per GL', 'NAICS Code', 'Average Net Deposits',
       'Funded Units', 'Gross Annual Sales', 'Portfolio Grade',
       'Avg Number of Deposits', 'Date_Started', 'Contract Number',
       'R360 Reliant Score', 'Primary Owner FICO Score', 'Corp Zip',
       'Submissions', 'Risk Tier', 'ISO Group', 'Lag Days', 'App Type',
       'FP Original Term (Months)', 'Paid %', 'FP Contract Number',
       'Account Status', 'Baseline Pace %', 'Original Advance Amount'],
      dtype='object')

In [1384]:
CreditRisk_df = CreditRisk_df.drop(['R360 Reliant Score', 'Sum_Balance Per GL', 'Corp Zip'], axis=1)
CreditRisk_df

,Funded Days,Avg Bank Balance,Avg Bank Negative Days,Max Sell Rate,Max Offer Amount,Date Funded,NAICS Code,Average Net Deposits,Funded Units,Gross Annual Sales,...,Risk Tier,ISO Group,Lag Days,App Type,FP Original Term (Months),Paid %,FP Contract Number,Account Status,Baseline Pace %,Original Advance Amount
0,1390.0,8453.56,0.17,1.370,21500.0,2017-10-05,484110.0,88760.00,1,1065120.0,...,NaN,WHO,0.0,NEW,10.0,1.00,MC171004025,WROFF,34.29,46000.0
1,1252.0,4682.50,0.00,1.524,8000.0,2018-02-20,423610.0,9879.19,1,118550.0,...,NaN,WHO,0.0,NEW,8.0,1.00,MC180216046,WROFF,25.11,3000.0
2,1648.0,7106.21,0.75,1.390,22000.0,2017-01-20,238990.0,42456.00,1,509472.0,...,NaN,WHO,0.0,NEW,7.0,1.00,MC170118065,WROFF,43.92,65000.0
3,1449.0,2067.44,0.00,1.440,11000.0,2017-08-07,238320.0,15344.20,1,184130.0,...,NaN,WHO,0.0,NEW,9.0,1.00,MC170727096,WROFF,86.01,15495.0
4,1449.0,9548.01,0.88,1.500,53000.0,2017-08-07,238110.0,71789.20,1,861470.0,...,NaN,WHO,0.0,NEW,10.0,1.00,MC170802165,WROFF,34.52,55000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24204,1008.0,8700.12,2.00,1.479,71000.0,2018-10-22,621610.0,68449.60,1,821395.0,...,Ultra-Low Risk,DIR,918.0,NEW,9.0,0.31,MC181005127,WROFF,43.56,NaN
24205,1088.0,1996.29,0.83,1.399,15395.0,2018-08-03,446191.0,14947.00,1,179364.0,...,Ultra-Low Risk,DIR,9.0,NEW,9.0,0.16,MC180731041,WROFF,52.50,NaN
24206,962.0,11387.10,0.86,1.489,15000.0,2018-12-07,453991.0,13685.10,1,312555.0,...,Ultra-Low Risk,DIR,763.0,NEW,12.0,0.54,MC181205127,WROFF,65.43,NaN
24207,1032.0,4666.67,0.00,1.479,48000.0,2018-09-28,448140.0,52577.40,1,630929.0,...,Ultra-Low Risk,DIR,987.0,NEW,8.0,0.13,MC180925221,WROFF,21.90,NaN
24208,1041.0,8514.15,0.83,1.479,101000.0,2018-09-19,238220.0,111379.00,1,1336550.0,...,Ultra-Low Risk,DIR,116.0,NEW,9.0,0.47,MC180914153,WROFF,82.14,NaN

In [1385]:
CreditRisk_df_Score =CreditRisk_df.groupby(["Risk Tier"]).mean()['Primary Owner FICO Score'].round(decimals=2)
CreditRisk_df_Score

Risk Tier
High A Risk       630.89
High B Risk       625.64
High Risk         629.72
Low               628.83
Low Risk          635.99
Medium            623.62
Medium A Risk     636.49
Medium B Risk     624.60
Medium Risk       639.68
Ultra-Low Risk    638.69
Name: Primary Owner FICO Score, dtype: float64

In [1386]:
CreditRisk_df.columns=CreditRisk_df.columns.str.strip()

In [1387]:
CreditRisk_df.groupby('ISO Group').size()

ISO Group
DIR    14148
WHO    10061
dtype: int64

In [1389]:
CreditRisk_df.groupby('Primary Owner FICO Score').mean()['Gross Annual Sales'].round(decimals=2)

Primary Owner FICO Score
0.0       200459.66
379.0     180257.00
397.0      45372.30
399.0     686023.00
400.0     514933.33
            ...
836.0     678167.00
839.0    4708000.00
840.0     389836.33
848.0    2374990.00
850.0     349594.50
Name: Gross Annual Sales, Length: 418, dtype: float64

In [1390]:
CreditRisk_df_Score =CreditRisk_df.groupby(["Account Status"]).mean()['Primary Owner FICO Score'].round(decimals=2)
CreditRisk_df_Score

Account Status
ACT       633.74
BUYOUT    634.22
DEF       633.90
OVRPD     493.00
PDOFF     634.90
SETT      636.30
WROFF     632.02
Name: Primary Owner FICO Score, dtype: float64

In [1391]:
from sklearn.preprocessing import LabelEncoder
Portfolio_dict = {'1':0,'2':0,'3':0,'4':1,'5':1,'6':1}

CreditRisk_df['Portfolio Grade'].replace(Portfolio_dict, inplace=True)

Risk_dict = {"High A Risk":0, "High B Risk":0, "High Risk":0, "Medium A Risk":1, "Medium B Risk":1, "Medium Risk":1, "Medium":1,
            "Low":2, "Low Risk":2,"Ultra-Low Risk":2 }
CreditRisk_df['Risk Tier'].replace(Risk_dict, inplace=True)

CreditRisk_df.head()

,Funded Days,Avg Bank Balance,Avg Bank Negative Days,Max Sell Rate,Max Offer Amount,Date Funded,NAICS Code,Average Net Deposits,Funded Units,Gross Annual Sales,...,Risk Tier,ISO Group,Lag Days,App Type,FP Original Term (Months),Paid %,FP Contract Number,Account Status,Baseline Pace %,Original Advance Amount
0,1390.0,8453.56,0.17,1.370,21500.0,2017-10-05,484110.0,88760.00,1,1065120.0,...,NaN,WHO,0.0,NEW,10.0,1.0,MC171004025,WROFF,34.29,46000.0
1,1252.0,4682.50,0.00,1.524,8000.0,2018-02-20,423610.0,9879.19,1,118550.0,...,NaN,WHO,0.0,NEW,8.0,1.0,MC180216046,WROFF,25.11,3000.0
2,1648.0,7106.21,0.75,1.390,22000.0,2017-01-20,238990.0,42456.00,1,509472.0,...,NaN,WHO,0.0,NEW,7.0,1.0,MC170118065,WROFF,43.92,65000.0
3,1449.0,2067.44,0.00,1.440,11000.0,2017-08-07,238320.0,15344.20,1,184130.0,...,NaN,WHO,0.0,NEW,9.0,1.0,MC170727096,WROFF,86.01,15495.0
4,1449.0,9548.01,0.88,1.500,53000.0,2017-08-07,238110.0,71789.20,1,861470.0,...,NaN,WHO,0.0,NEW,10.0,1.0,MC170802165,WROFF,34.52,55000.0

In [1392]:
APP_dict = {'NEW':0,'RENEW':1, 'CONC':2}

CreditRisk_df['App Type'].replace(APP_dict, inplace=True)

ISO_dict = {'WHO':0, 'DIR':1}
CreditRisk_df['ISO Group'].replace(ISO_dict, inplace=True)

CreditRisk_df.head()

,Funded Days,Avg Bank Balance,Avg Bank Negative Days,Max Sell Rate,Max Offer Amount,Date Funded,NAICS Code,Average Net Deposits,Funded Units,Gross Annual Sales,...,Risk Tier,ISO Group,Lag Days,App Type,FP Original Term (Months),Paid %,FP Contract Number,Account Status,Baseline Pace %,Original Advance Amount
0,1390.0,8453.56,0.17,1.370,21500.0,2017-10-05,484110.0,88760.00,1,1065120.0,...,NaN,0,0.0,0,10.0,1.0,MC171004025,WROFF,34.29,46000.0
1,1252.0,4682.50,0.00,1.524,8000.0,2018-02-20,423610.0,9879.19,1,118550.0,...,NaN,0,0.0,0,8.0,1.0,MC180216046,WROFF,25.11,3000.0
2,1648.0,7106.21,0.75,1.390,22000.0,2017-01-20,238990.0,42456.00,1,509472.0,...,NaN,0,0.0,0,7.0,1.0,MC170118065,WROFF,43.92,65000.0
3,1449.0,2067.44,0.00,1.440,11000.0,2017-08-07,238320.0,15344.20,1,184130.0,...,NaN,0,0.0,0,9.0,1.0,MC170727096,WROFF,86.01,15495.0
4,1449.0,9548.01,0.88,1.500,53000.0,2017-08-07,238110.0,71789.20,1,861470.0,...,NaN,0,0.0,0,10.0,1.0,MC170802165,WROFF,34.52,55000.0

In [1393]:
CreditRisk_df['Date_Started'] = pd.to_datetime(CreditRisk_df['Date_Started'],infer_datetime_format=True)
CreditRisk_df['Date_Started']=CreditRisk_df['Date_Started'].apply(lambda x: x.toordinal())
CreditRisk_df.dtypes

Funded Days                         float64
Avg Bank Balance                    float64
Avg Bank Negative Days              float64
Max Sell Rate                       float64
Max Offer Amount                    float64
Date Funded                  datetime64[ns]
NAICS Code                          float64
Average Net Deposits                float64
Funded Units                          int64
Gross Annual Sales                  float64
Portfolio Grade                     float64
Avg Number of Deposits              float64
Date_Started                          int64
Contract Number                      object
Primary Owner FICO Score            float64
Submissions                           int64
Risk Tier                           float64
ISO Group                             int64
Lag Days                            float64
App Type                              int64
FP Original Term (Months)           float64
Paid %                              float64
FP Contract Number                   object
Account Status                       object
Baseline Pace %                     float64
Original Advance Amount             float64
dtype: object

In [1394]:
CreditRisk_df = CreditRisk_df.dropna()
CreditRisk_df

,Funded Days,Avg Bank Balance,Avg Bank Negative Days,Max Sell Rate,Max Offer Amount,Date Funded,NAICS Code,Average Net Deposits,Funded Units,Gross Annual Sales,...,Risk Tier,ISO Group,Lag Days,App Type,FP Original Term (Months),Paid %,FP Contract Number,Account Status,Baseline Pace %,Original Advance Amount
21,1412.0,2997.43,0.33,1.420,25500.0,2017-09-13,485999.0,64065.30,1,768783.0,...,2.0,0,0.0,0,8.0,1.0,MC170911029,ACT,14.98,3000.0
22,1524.0,8838.50,0.25,1.470,12500.0,2017-05-24,484110.0,59380.70,1,712568.0,...,2.0,0,0.0,0,12.0,1.0,MC170523049,ACT,100.00,8000.0
25,1621.0,35106.60,0.00,1.420,20000.0,2017-02-16,423450.0,28115.00,1,337379.0,...,2.0,0,0.0,0,8.0,1.0,MC170210035,ACT,100.00,30000.0
26,1496.0,23386.10,0.75,1.420,35500.0,2017-06-21,611699.0,89483.80,1,1073810.0,...,2.0,0,0.0,0,8.0,1.0,MC170613027,ACT,100.00,10000.0
27,1363.0,5285.89,0.00,1.430,50000.0,2017-11-01,621330.0,124233.00,1,1490790.0,...,2.0,0,0.0,0,8.0,1.0,MC171020131,ACT,100.00,8000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12181,1144.0,5859.19,0.13,1.319,15000.0,2018-06-08,488390.0,18297.10,1,219565.0,...,2.0,1,0.0,1,7.0,1.0,MC180607121,WROFF,20.67,10000.0
12182,312.0,3460.33,0.00,1.359,10000.0,2020-09-17,484110.0,6876.09,1,82513.1,...,2.0,1,0.0,1,6.0,1.0,MC200917059,WROFF,82.69,90000.0
12183,620.0,13373.50,0.00,1.279,91000.0,2019-11-14,484110.0,92272.40,1,1107270.0,...,2.0,1,0.0,1,6.0,1.0,MC191112285,WROFF,64.72,10000.0
12184,837.0,5787.11,1.14,1.359,46000.0,2019-04-11,484121.0,57426.70,1,689120.0,...,2.0,1,0.0,1,6.0,1.0,MC190409212,WROFF,58.50,144000.0
12185,500.0,12826.30,0.00,1.269,50000.0,2020-03-13,484110.0,101732.00,1,1220780.0,...,2.0,1,0.0,1,7.0,1.0,MC200219004,WROFF,66.12,13000.0

In [1460]:
X = CreditRisk_df[['Avg Bank Balance','Avg Bank Negative Days','Average Net Deposits','ISO Group',
                 'Date_Started','Primary Owner FICO Score','Gross Annual Sales','Original Advance Amount',
                   'Risk Tier','Lag Days','Baseline Pace %']]
y = CreditRisk_df[['Portfolio Grade']]

In [1461]:
X.describe()

,Avg Bank Balance,Avg Bank Negative Days,Average Net Deposits,ISO Group,Date_Started,Primary Owner FICO Score,Gross Annual Sales,Original Advance Amount,Risk Tier,Lag Days,Baseline Pace %
count,1.097200e+04,10972.000000,1.097200e+04,10972.000000,10972.000000,10972.000000,1.097200e+04,10972.000000,10972.000000,10972.000000,10972.000000
mean,1.363364e+04,0.588285,5.609130e+04,0.617116,734291.589956,635.868848,6.814497e+05,28821.322384,1.745899,111.229311,104.766556
std,4.437201e+04,1.217454,1.096874e+05,0.486112,3175.114757,71.620897,1.431472e+06,33228.499619,0.549240,283.453063,57.566246
min,-1.720720e+03,0.000000,0.000000e+00,0.000000,690759.000000,0.000000,0.000000e+00,1500.000000,0.000000,0.000000,0.000000
25%,2.336847e+03,0.000000,1.536358e+04,0.000000,733255.000000,593.000000,1.847792e+05,10000.000000,2.000000,0.000000,100.000000
50%,5.130485e+03,0.000000,2.786995e+04,1.000000,735390.000000,641.000000,3.353015e+05,17500.000000,2.000000,0.000000,100.000000
75%,1.245988e+04,0.670000,5.711857e+04,1.000000,736334.250000,681.000000,6.884412e+05,34323.750000,2.000000,0.000000,100.000000
max,2.403990e+06,23.000000,4.500750e+06,1.000000,737621.000000,850.000000,5.868320e+07,300000.000000,2.000000,1576.000000,2100.000000

In [1462]:
from sklearn.preprocessing import StandardScaler
standar_scaler=StandardScaler()
scaled_X = standar_scaler.fit_transform(X)

In [1463]:
X =pd.DataFrame(scaled_X, columns=X.columns)
X.describe()

,Avg Bank Balance,Avg Bank Negative Days,Average Net Deposits,ISO Group,Date_Started,Primary Owner FICO Score,Gross Annual Sales,Original Advance Amount,Risk Tier,Lag Days,Baseline Pace %
count,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04,1.097200e+04
mean,-8.971170e-18,-2.962151e-15,-4.551388e-17,5.301467e-15,8.131766e-15,-2.351584e-16,-2.222065e-17,2.199804e-17,7.191456e-16,-5.695711e-16,-3.223310e-15
std,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00,1.000046e+00
min,-3.460529e-01,-4.832310e-01,-5.113973e-01,-1.269551e+00,-1.371118e+01,-8.878663e+00,-4.760698e-01,-8.222631e-01,-3.178897e+00,-3.924261e-01,-1.820013e+00
25%,-2.546044e-01,-4.832310e-01,-3.713241e-01,-1.269551e+00,-3.264881e-01,-5.985795e-01,-3.469806e-01,-5.664469e-01,4.626626e-01,-3.924261e-01,-8.280500e-02
50%,-1.916421e-01,-4.832310e-01,-2.573006e-01,7.876802e-01,3.459592e-01,7.164649e-02,-2.418237e-01,-3.407267e-01,4.626626e-01,-3.924261e-01,-8.280500e-02
75%,-2.645404e-02,6.712286e-02,9.365877e-03,7.876802e-01,6.433636e-01,6.301682e-01,4.884390e-03,1.656012e-01,4.626626e-01,-3.924261e-01,-8.280500e-02
max,5.387327e+01,1.840951e+01,4.052298e+01,7.876802e-01,1.048643e+00,2.989922e+00,4.052079e+01,8.161399e+00,4.626626e-01,5.167831e+00,3.466136e+01

In [1488]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler


X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=0)

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1489]:
X_train.shape, y_train.shape

((7680, 11), (7680, 1))

In [1490]:
X_test.shape, y_test.shape

((3292, 11), (3292, 1))

In [1496]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [1495]:
y_pred = model.predict(X_test)

In [1493]:
accuracy_score(y_test,y_pred, normalize=True) * 100

86.2089914945322

In [1492]:
print("Training score:", model.score(X_train, y_train))

Training score: 0.8623697916666667

In [1494]:
parameters = {'splitter': ('best','random'),
             'max_depth': [2,4,6],
             'max_features':[2,4,6, None]}

grid_search = GridSearchCV(DecisionTreeClassifier(), parameters, cv=5,
                          return_train_score=True)
grid_search.fit(X_train, y_train)

grid_search.best_params_

{'max_depth': 4, 'max_features': None, 'splitter': 'best'}

In [1497]:
model = DecisionTreeClassifier(splitter=grid_search.best_params_['splitter'],
                                       max_depth=grid_search.best_params_['max_depth'],
                                      max_features=grid_search.best_params_['max_features'])

X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0)

In [1498]:
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4)

In [1499]:
y_train_hat = model.predict(X_train)
y_pred = model.predict(X_test)

in_sample_acc = accuracy_score(y_train,y_train_hat, normalize=True) * 100

out_of_sample_acc = accuracy_score(y_test,y_pred, normalize=True) * 100

print("In-sample Accuracy:", in_sample_acc)
print("Out-of-sample Accuracy:", out_of_sample_acc)

In-sample Accuracy: 88.41900595455098
Out-of-sample Accuracy: 87.93292016040832

In [1500]:
feature_names = CreditRisk_df[['Avg Bank Balance','Avg Bank Negative Days','Average Net Deposits','ISO Group',
                 'Date_Started','Primary Owner FICO Score','Gross Annual Sales','Original Advance Amount',
                   'Risk Tier','Lag Days','Baseline Pace %']]

In [1501]:
#print(feature_names)
model.feature_importances_

array([7.47843670e-04, 1.58780684e-03, 0.00000000e+00, 3.66124656e-03,
       9.62175918e-04, 8.92563880e-04, 0.00000000e+00, 3.11337351e-03,
       2.84814661e-03, 9.83375197e-01, 2.81164604e-03])

In [1477]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=0)

model.fit(X_train, y_train)

y_train_hat = model.predict(X_train)
y_pred = model.predict(X_test)

in_sample_acc = accuracy_score(y_train,y_train_hat, normalize=True) * 100

out_of_sample_acc = accuracy_score(y_test,y_pred, normalize=True) * 100
print("In-sample Accuracy:", in_sample_acc)
print("Out-of-sample Accuracy:", out_of_sample_acc)

In-sample Accuracy: 100.0
Out-of-sample Accuracy: 88.22457163689391

In [40]:
#len(CreditRisk_df['contract_number'].unique())

In [ ]:
#CreditRisk_df = CreditRisk_df.columns.str.replace(' ','_', inplace=True)
#CreditRisk_df

In [ ]:
from sklearn import tree
import graphviz
#fig = plt.figure(figsize=(25,20))

#class_names = ['0','1']
#feature_names = 
#dot_data = tree.export_graphviz(model, 
                  #feature_names=feature_names, 
                  #class_names=class_names,  
                  #filled=True, rounded=True,  
                  #special_characters=True,
                  #out_file=None)
                           
#graph = graphviz.Source(dot_data)
#graph